### ISSUE TITLE
Supporting binding VIP or HOSTNAME

### ISSUE THREAD

**Issue by jingwen-li** [dubbo/dubbo-rpc-native-thrift#9]
Current, I find the implementation is only support protocol port setting, like
         <dubbo:protocol name="nthrift" port="8899" />
But not support "host" option, like 
        <dubbo:protocol name="nthrift" port="8899" host="127.0.0.1"/>

Could change
`args.port(url.getPort());` 
to 
`args.bindAddr(new InetSocketAddress(url.getHost(), url.getPort()));`

BTW: It seems: url.getHost() is always not null, whatever the settings are including the host option or not

**Comment by lovepoem** [comment]
hi, @jingwen-li  would you please send a pull request ?

**Comment by lovepoem** [comment]
close via https://github.com/dubbo/dubbo-rpc-native-thrift/pull/12
